#!/bin/bash

(
  mkdir /tmp/$$ &&
  cd /tmp/$$ &&
  if ! [ -z "$APOS_MONGODB_URI" ]; then
    export APOS_MONGODB_URI="${APOS_MONGODB_URI/apostrophe-enterprise-testbed/test}"
  fi
  git clone https://github.com/apostrophecms/apostrophe-headless &&
  cd apostrophe-headless &&
  npm install &&
  npm install apostrophecms/apostrophe &&
  npm test &&
  rm -rf /tmp/$$
) || FAIL=1

rm -rf /tmp/$$

if [ -n "$FAIL" ]; then
  exit 1
fi


