#!/bin/bash

(
  mkdir /tmp/$$ &&
  cd /tmp/$$ &&
  git clone https://github.com/apostrophecms/apostrophe-headless &&
  cd apostrophe-headless &&
  npm install &&
  npm install apostrophecms/apostrophe &&
  npm test &&
  rm rm -rf /tmp/$$
) || FAIL=1

rm -rf /tmp/$$

if [ -n "$FAIL" ]; then
  exit 1
fi


