#!/bin/bash

# Make sure the webserver process dies when we exit
trap 'kill $(jobs -p)' EXIT

# Create an asset bundle the recommended way
APOS_BUNDLE=1 node app apostrophe:generation || exit 1
# Fire up the site using that bundle's assets
APOS_BUNDLE=1 node app &
sleep 10
# Verify we can get the home page
wget http://localhost:3000 -O /tmp/$$.html || exit 1
# http://localhost:3000/uploads/assets/ck199jeiq00013quk6zgkmbd2/apos-minified/anon-ck199jeiq00013quk6zgkmbd2.css
if ! grep -P "uploads/assets/.*/apos-minified/anon-.*.css" /tmp/$$.html ; then
  echo "Output does not load anon CSS from bundle"
  exit 1
fi
LINE=`grep -P "uploads/assets/.*/apos-minified/anon-.*.css" /tmp/$$.html`
MATCH=`echo $LINE | grep -o -P 'http[^"]+'` 
wget $MATCH -O /dev/null || exit 1
echo "Good CSS from bundle"

if ! grep -P "uploads/assets/.*/apos-minified/anon-.*.js" /tmp/$$.html ; then
  echo "Output does not load anon JS from bundle"
  exit 1
fi
LINE=`grep -P "uploads/assets/.*/apos-minified/anon-.*.js" /tmp/$$.html`
echo "Line is $LINE"
MATCH=`echo $LINE | grep -o -P 'http[^"]+'` 
wget $MATCH -O /dev/null || exit 1
echo "Good JS from bundle"

# Don't litter or we'll break dev assets
rm data/generation || exit 1
rm -rf public/modules || exit 1

