language: node_js
node_js:
- stable
sudo: false
services:
- docker
- mongodb
addons:
  sauce_connect: true
branches:
  only:
  - master
env:
  global:
    secure: FIWV+wHoXfJdGj4vyqMAvOnfg1nxQ5ZaUhGEzzdPWoI08NsFlY6rFQXoJEULVoqnUeeIPKKPGBzTr7eNuuRqB54NRI+qa5k6hpCQD2akoiNv5cUsyXgWc4jrYBIzdfUGpa3NnNejmGpXIw/zkZWyUHT8CrxajDruVIIwaHaqFgD9O3a+12+9iv94WpjTUCZP6tdGZcUp1KY2VVyMdt7rdz7Mvwh+bobKGBxzWT/rxY+CZ1D3GzdM1ktYpG+YPxg4UvZjoAXPFrwy/uPWeNpd/sGJETDhm3DMY2dVmK4SKkTDvPa69z7Bjg9NaH3TuILrOOPKdvGRdtzXc8eKrpbkDR7s3gTebJ/F/sGHTuemg5klCRbYn/HIwRnoa1fM2wT3SjzGcdqzV5Gkwrwacd988/3gSHGiyA4EsI1q2X9DDDlPHofhiD3byUwv/nRhlqO01jLwbHbBqdTD4dWiA8MzMbO7+Jow16UpkKmyRJYuAYPnsHp4cyixinbOdtcVZdY2Ue84nUwaXFhAKOd3xT+Vw9BQQTmCsPIaWS9niQzY6YlSHZzbP1AwBmjJ2NyXnYO9aMlSj3aBsNtoG1eEIcb+fvJB1K7sCqi9CyyxzlyMJbwaj2M/EdU/X4npMb3w7p53yuNeLdM0ODVp6dPNcRbhiht4emiZqoh9h8vUixckKt4=
