#!/bin/bash

mkdir -p screenshots/latest

if [ -z "$TEST" ]; then
  tests=tests/scenarios/* 
else
  tests=tests/scenarios/$TEST.spec.js
fi

npx nightwatch $tests --config nightwatch.js --env $VISUAL_ENV &&

echo "Nightwatch functional tests PASSED"
