version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
      - image: mongo:3.6.11
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: install-mongo-cli
          command: 'sudo ci-helpers/install-mongo-cli.bash'
      - restore_cache:
          key: proj-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: proj-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test-polymorphic
