module.exports = {
  main: require('./main'),
  login: require('./login'),
  switchToDraftMode: require('./switchToDraftMode'),
  switchToLiveMode: require('./switchToLiveMode'),
  switchLocale: require('./switchLocale'),
  makeSubPage: require('./makeSubPage'),
  changePageTypeTo: require('./changePageTypeTo'),
  submitChanges: require('./submitChanges'),
  checkSubmitted: require('./checkSubmitted'),
  confirm404ByRelativeUrl: require('./confirm404ByRelativeUrl'),
  confirm200ByRelativeUrl: require('./confirm200ByRelativeUrl'),
  navigateToRelativeUrl: require('./navigateToRelativeUrl'),
  navigateToRelativeUrlAndconfirm404: require('./navigateToRelativeUrlAndconfirm404'),
  navigateToRelativeUrlAndconfirm200: require('./navigateToRelativeUrlAndconfirm200'),
  navigateToPage: require('./navigateToPage'),
  navigateToHome: require('./navigateToHome'),
  commit: require('./commit'),
  commitAndExport: require('./commitAndExport'),
  addTextWidgetTo: require('./addTextWidgetTo'),
  checkNotification: require('./checkNotification'),
  createArticle: require('./createArticle'),
  makeIncognitoRequestByRelativeUrl: require('./makeIncognitoRequestByRelativeUrl'),
  openContextMenu: require('./openContextMenu'),
  workflowSubmitArticle: require('./workflowSubmitArticle'),
  workflowCommitArticle: require('./workflowCommitArticle')
};
