module.exports = {
  main: require('./main'),
  login: require('./login'),
  switchToDraftMode: require('./switchToDraftMode'),
  switchToLiveMode: require('./switchToLiveMode'),
  switchLocale: require('./switchLocale'),
  makeSubPage: require('./makeSubPage'),
  submitChanges: require('./submitChanges'),
  checkSubmitted: require('./checkSubmitted'),
  confirm404ByRelativeUrl: require('./confirm404ByRelativeUrl'),
  confirm200ByRelativeUrl: require('./confirm200ByRelativeUrl'),
  navigateToPage: require('./navigateToPage'),
  navigateToHome: require('./navigateToHome'),
  commitChanges: require('./commitChanges'),
  addTextWidgetTo: require('./addTextWidgetTo'),
  checkNotification: require('./checkNotification'),
  createArticle: require('./createArticle'),
};
